[config]
default_to_workspace = false

[tasks.default]
alias = "build"

[tasks.build]
dependencies = ["build-compiler", "build-runtime"]

[tasks.build-compiler]
command = "cargo"
args = ["build", "--bin", "airyc-compiler"]

[tasks.build-runtime]
command = "cargo"
args = ["build", "-p", "runtime"]

[tasks.test]
description = "Run all integration tests"
dependencies = ["build"]
command = "cargo"
args = [
    "run",
    "-p",
    "test",
    "--",
    "--test-dir",
    "./testcases",
    "--exclude",
    "performance",
    "--compiler",
    "./target/debug/airyc-compiler",
    "--runtime",
    "./target/debug/libruntime.a",
    "--timeout",
    "20",
    "--verbose"
]

